## Imports

In [34]:
import pandas as pd
pd.options.display.max_colwidth = 500


df_text_versions = pd.read_csv("deep_course_cf_text_versions.csv", low_memory = False)

df_text_versions_node = pd.read_csv("deep_course_cf_text_version_nodes.csv", low_memory = False)

df_themes = pd.read_csv("deep_course_cf_themes.csv", low_memory = False)

df_types = pd.read_csv("deep_course_cf_types.csv", low_memory = False)

df_nodes = pd.read_csv("deep_course_cm_nodes.csv", low_memory = False)


df_formulaire_question = pd.read_csv("deep_course_formulaire_question.csv", low_memory = False)

df_formulaire_questionnaire = pd.read_csv("deep_course_formulaire_questionnaire.csv", low_memory = False)

df_formulaire_questionnaire_pages = pd.read_csv("deep_course_formulaire_questionnaire_pages.csv", low_memory = False)

df_formulaire_question_choix = pd.read_csv("deep_course_formulaire_question_choix.csv", low_memory = False)

df_formulaire_reponse = pd.read_csv("deep_course_formulaire_reponse.csv", low_memory = False)

df_formulaire_page_questions = pd.read_csv("deep_course_formulaire_page_questions.csv", low_memory = False)

## Explorations des bases

In [17]:
df_text_versions.head(2)
#base des textes réglementaires avec leur titre, ID, id du thème et le id du type de document (applicable ou non)

,surrogate_uuid,group_id,txt_name,theme_id,type_id
0,2c90f588404b484801404d8600d87748,TXA9548,RÈGLEMENT (UE) N°715/2013 DE LA COMMISSION du 25 juillet 2013 établissant les critères permettant de déterminer à quel moment les débris de cuivre cessent d’être des déchets au sens de la directive 2008/98/CE du Parlement européen et du Conseil,4028807d16245e4d01162524c71b6a4d,4028807d16245e4d01162524ed896c33
1,2c90f588404b484801404dce49f11efc,TXA9550,Arrêté du 16 juillet 2013 fixant le barème hors taxes des redevances prévues à l'article L. 554-5 du code de l'environnement pour l'année 2013,ff8081816b4d71ef016b54e0b788416d,4028807d16245e4d01162524db946b37

In [13]:
df_text_versions.describe()

,surrogate_uuid,group_id,txt_name,theme_id,type_id
count,3515,3515,3515,3515,3515
unique,3515,3515,3485,53,17
top,2c90f588592da60801595e77e38273a7,TXA8836,Arrêté du 26 février 2009 portant agrément d'un organisme pour effectuer le contrôle périodique de certaines catégories d'installations classées soumises à déclaration,4028807d16245e4d01162524c9ec6a71,4028807d16245e4d01162524db946b37
freq,1,1,6,550,1079

In [18]:
df_text_versions_node.head()
# id du texte réglementaire et id du compte client dans lequel il est présent

         txt_version_surrogate_uuid                       txt_node_id
0  d37394453d6ac204013d6d847b0a4b3a  2c90f5883f44af68013f564a1326558a
1  d37394453a046068013a0c21f6824adc  2c90f5883f44af68013f564a1326558a
2  d37394453c64588f013c70d1f1b31b49  2c90f5883f44af68013f564a1326558a
3  d3739445374d5348013783ef84d41b5c  2c90f5883f44af68013f564a1326558a
4  d373944539678fdb0139a42ace673d21  2c90f5883f44af68013f564a1326558a

In [19]:
df_text_versions_node.describe()

              txt_version_surrogate_uuid                       txt_node_id
count                             329942                            329942
unique                              7369                               573
top     2c90f58864274849016427cf71e44af4  4028807d16245e4d0116249e4259205e
freq                                 555                              1641

In [20]:
df_themesn #base des thèmes des textes

,id,domain,theme
0,4028807d16245e4d01162524d4216aef,3. SÉCURITÉ,CSE / CHSCT
1,d37394c53120b52601313c3107f77043,3. SÉCURITÉ,Remontées mécaniques - Transports guidés/personnes
2,4028807d16245e4d01162524d6f26b13,4. INSPECTION,Equipements sous pression
3,d37394c5208c61e80120f1fb613810d9,8. SECURITE ALIMENTAIRE,Sécurité alimentaire
4,4028807d16245e4d01162524cd016a95,3. SÉCURITÉ,Personnel
5,4028807d16245e4d01162524cc546a8c,3. SÉCURITÉ,Locaux
6,4028807d16245e4d01162524ce806aa7,3. SÉCURITÉ,"Equipements de travail, Machines, outils"
7,4028807d16245e4d01162524cbab6a83,3. SÉCURITÉ,Principes Généraux Sécurité
8,4028807d16245e4d01162524cdc16a9e,3. SÉCURITÉ,Incendie/Explosion
9,4028807d16245e4d01162524cfda6ab9,3. SÉCURITÉ,Risques biologiques
10,4028807d16245e4d01162524d1416acb,3. SÉCURITÉ,Entreprises extérieures
11,4028807d16245e4d01162524d2c46add,3. SÉCURITÉ,Service de santé au travail
12,4028807d16245e4d01162524d4d36af8,3. SÉCURITÉ,Appareils de levage
13,4028807d16245e4d01162524d5946b01,3. SÉCURITÉ,Installations électriques
14,d37394c522a42328012338c87f4c2c22,3. SÉCURITÉ,Amiante
15,d37394c522a42328012338c8c7d32c28,3. SÉCURITÉ,Rayonnements non ionisants
16,d37394c522a42328012338c907e42c2e,3. SÉCURITÉ,Radioprotection
17,d37394c522a42328012338c96bac2c34,3. SÉCURITÉ,Bruit et vibrations mécaniques
18,d37394c522a42328012338c9b9af2c3a,3. SÉCURITÉ,Equipements de protection individuelle
19,d37394c522a42328012338c9f3d72c40,3. SÉCURITÉ,ERP - IGH
20,2c90f58951ea3d5101521fc686436f02,6. ENERGIE,Approvisionnement / Raccordement
21,d37394453d863f29013daaf2faf0518e,6. ENERGIE,RT des bâtiments
22,d37394453d863f29013daaf371e951b9,6. ENERGIE,Mécanismes économiques
23,d37394453d863f29013daaf3cf6451fe,6. ENERGIE,ENR - Cogénération
24,d37394453d863f29013daaf338a251a6,6. ENERGIE,Equipements énergétiques
25,d37394c522a42328012338c619a32c1c,6. ENERGIE,Dispositions générales
26,d37394d91d01347d011d633ba1ce6608,5. TRANSPORT DE MARCHANDISES DANGEREUSES ET AUTRES,Transport MD
27,4028807d16245e4d01162524c5ba6a3b,1. ENVIRONNEMENT,Eau
28,4028807d16245e4d01162524c7d96a56,1. ENVIRONNEMENT,Principes Généraux Environnement
29,4028807d16245e4d01162524c4c46a32,1. ENVIRONNEMENT,Pollution atmosphérique
30,4028807d16245e4d01162524c6706a44,1. ENVIRONNEMENT,Bruit et vibrations
31,4028807d16245e4d01162524c8846a5f,1. ENVIRONNEMENT,Risques technologiques
32,4028807d16245e4d01162524c92d6a68,1. ENVIRONNEMENT,Nature et biodiversité
33,4028807d16245e4d01162524c9ec6a71,1. ENVIRONNEMENT,Installations classées
34,d37394c522a42328012338c3d2842c04,1. ENVIRONNEMENT,Combustion
35,d37394c522a42328012338c482ba2c10,1. ENVIRONNEMENT,Sites et sols pollués
36,4028807d16245e4d01162524d8566b25,1. ENVIRONNEMENT,OGM
37,4028807d16245e4d01162524d7ad6b1c,1. ENVIRONNEMENT,Taxes
38,d373944536c784aa0136e8c822392683,2. PRODUITS CHIMIQUES,Produits explosifs
39,4028807d16245e4d01162524cb036a7a,2. PRODUITS CHIMIQUES,Risques chimiques / Substances particulières
40,2c90f588422a462a014232c34f995161,3. SÉCURITÉ,Sécurité routière
41,2c90f588558d4ff9015590e55bbc7031,1. ENVIRONNEMENT,"Sous-sol, mines et carrières"
42,ff80818167b26ea801680f0eaad46854,7. SÛRETÉ,Sûreté : Dispositions générales
43,ff80818167b26ea801680f0ffa6b69e0,7. SÛRETÉ,Accès (systèmes de contrôle ...)
44,ff80818167b26ea801680f1076556a3d,7. SÛRETÉ,Vidéosurveillance / Télésurveillance
45,ff80818167b26ea801680f10c83a6ac6,7. SÛRETÉ,Etablissements sensibles
46,ff80818167b26ea801680f1159662343,7. SÛRETÉ,Surveillance et gardiennage
47,ff80818167b26ea801680f11eb7e3160,7. SÛRETÉ,Sûreté portuaire
48,ff8081816b4d71ef016b54dc08db3a27,5. TRANSPORT DE MARCHANDISES DANGEREUSES ET AUTRES,Voies ferrées
49,ff8081816b4d71ef016b54dd71e53d99,1. ENVIRONNEMENT,Canalisations de transport
50,ff8081816b4d71ef016b54e01560411b,1. ENVIRONNEMENT,Risques naturels
51,ff8081816b4d71ef016b54e0b788416d,1. ENVIRONNEMENT,Travaux à proximité des réseaux / Guichet unique
52,4028807d16245e4d01162524c71b6a4d,1. ENVIRONNEMENT,Déchets

In [22]:
df_types  #id du type de document, applicabilité ou non

                                  id     applicabilité
0   2c90f58962265e150162520dfe7c6281  Pour information
1   4028807d16245e4d01162524e20d6b91        Applicable
2   4028807d16245e4d01162524db946b37        Applicable
3   4028807d16245e4d01162524de2f6b5b        Applicable
4   4028807d16245e4d01162524df706b6d        Applicable
5   4028807d16245e4d01162524e0ba6b7f        Applicable
6   4028807d16245e4d01162524e7276bd9        Applicable
7   4028807d16245e4d01162524ec3c6c21  Pour information
8   d37394c5272f761f01273d899b5811d1  Pour information
9   4028807d16245e4d01162524eec86c45  Pour information
10  4028807d16245e4d01162524e48d6bb5        Applicable
11  4028807d16245e4d01162524e5e76bc7  Pour information
12  4028807d16245e4d01162524ed896c33        Applicable
13  4028807d16245e4d01162524f15c6c69  Pour information
14  4028807d16245e4d01162524e9ba6bfd        Applicable
15  4028807d16245e4d01162524f00a6c57        Applicable
16  4028807d16245e4d01162524e34f6ba3  Pour information

In [28]:
df_nodes #structure du questionnaire (numéro de la question, id page de la question, id question)

                                   id node_status
0    2c90f5883f44af68013f564a1326558a        SITE
1    2c90f5883fcf3281013fe7c2f0eb4dbe        SITE
2    2c90f588404b48480140ce4d7d301013        SITE
3    2c90f5884109d2c401410c40ae942d95        SITE
4    2c90f5884109d2c401410c4434a433a6        SITE
..                                ...         ...
592  ff80818174e6040901750227f26959d6        SITE
593  ff80818174e604090175022989a25da1        SITE
594  ff80818174e604090175036af76b3803        SITE
595  ff808181751301e9017522740a11111d        SITE
596  ff8081817528e71501754135cdfb6d7b        SITE

[597 rows x 2 columns]

In [24]:
df_nodes.describe()

                                      id node_status
count                                597         597
unique                               597           3
top     d37394c52dba36fd012dec60b8dc4223        SITE
freq                                   1         586

In [27]:
df_nodes.node_status.unique()

array(['SITE', 'GROUP', 'ABOVE_SITE'], dtype=object)

In [35]:
df_formulaire_question #contenu des questions

,aide,enonce_groupe,enonce_site,type,unite,id
0,NaN,Intervenez-vous (vos salariés) sur des matériaux amiantés (travaux de maintenance de bâtiments ou de machines pouvant contenir de l'amiante...) ?,Intervenez-vous (vos salariés) sur des matériaux amiantés (travaux de maintenance de bâtiments ou de machines pouvant contenir de l'amiante...) ?,1,NaN,006F52E9102A8D3BE2FE5614F42BA989
1,NaN,"De quelles sources (scellées, non scellées) ou appareils (accélérateurs de particules, générateurs de rayons X) s'agit-il?","De quelles sources (scellées, non scellées) ou appareils (accélérateurs de particules, générateurs de rayons X) s'agit-il?",0,NaN,01161AAA0B6D1345DD8FE4E481144D84
2,NaN,NaN,Le site est-il localisé sur une zone sismique ? Merci de préciser le type de classe.,1,NaN,013D407166EC4FA56EB1E1F8CBE183B9
3,NaN,Etes-vous soumis ou avez-vous un plan de prévention des risques naturels (PPRN) ?,Etes-vous soumis ou avez-vous un plan de prévention des risques naturels (PPRN) ?,1,NaN,02522A2B2726FB0A03BB19F2D8D9524D
4,NaN,NaN,Plans et localisation des bâtiments communiqués à Tennaxia,0,NaN,0266E33D3F546CB5436A10798E657D97
...,...,...,...,...,...,...
311,NaN,Votre entreprise est-elle soumise à l'obligation de conclure un accord ou d'élaborer un plan d'actions relatif de la prévention de la pénibilité ? \n (Obligation en fonction du pourcentage de salariés exposés ou de l'indice de sinistralité au niveau de l'entreprise),Votre entreprise est-elle soumise à l'obligation de conclure un accord ou d'élaborer un plan d'actions relatif de la prévention de la pénibilité ? \n (Obligation en fonction du pourcentage de salariés exposés ou de l'indice de sinistralité au niveau de l'entreprise),1,NaN,FC221309746013AC554571FBD180E1C8
312,NaN,Quelle(s) autre(s) rubrique(s) ICPE 3000 concern(ent) au moins l'un de vos sites ?,Quelle(s) autre(s) rubrique(s) ICPE 3000 concern(ent) votre site ?,0,NaN,FC490CA45C00B1249BBE3554A4FDF6FB
313,NaN,De quelle convention collective relève votre entreprise ?,De quelle convention collective relève votre entreprise ?,0,NaN,FD86425BAD0511E7B3CE001851D17886
314,NaN,Quelles sont les technologies utilisées pour l'éclairage des locaux (LED ….),Quelles sont les technologies utilisées pour l'éclairage des locaux (LED ….),0,NaN,FE131D7F5A6B38B23CC967316C13DAE2
315,NaN,Quels sont vos principaux polluants atmosphériques ?,Quels sont vos principaux polluants atmosphériques ?,0,NaN,FE9FC289C3FF0AF142B6D3BEAD98A923

In [39]:
df_formulaire_questionnaire #grandes parties du questionnaire

,couleur,nom,position,node_id,id
0,#999999,INFORMATIONS GENERALES,0,4028807d16245e4d0116247888d0793d,5E0F845AA9A537AAD2DD3E0FB248A44E
1,#009900,ENVIRONNEMENT,2,4028807d16245e4d0116247888d0793d,77D3F03B15B1CFEE59C5D16D0BE37123
2,#cc3333,SECURITE,3,4028807d16245e4d0116247888d0793d,7FAE1993C5027CE676D551A2BDFE6C04
3,#0066ff,ENERGIE,5,4028807d16245e4d0116247888d0793d,ABD03ACB00C00FE88EB701362C91F463
4,#6600CC,SURETE - MALVEILLANCE,4,4028807d16245e4d0116247888d0793d,C540C42A14EA11E9B4A4FA163E3BC92C
5,#ff6600,HSE,1,4028807d16245e4d0116247888d0793d,D597C271A829F7FBE0C01FD4109854EE

In [42]:
df_formulaire_questionnaire_pages  #ordre des pages d’un questionnaire
#questionnaire_id = id de la partie dans la base précédente ?

,page_order,questionnaire_id,pages_id
0,7,7FAE1993C5027CE676D551A2BDFE6C04,03C4AD7888A7E4C54975A8DDC0B7FD89
1,6,7FAE1993C5027CE676D551A2BDFE6C04,07B1E039C8678D21175FB8EBBB4E06FC
2,5,7FAE1993C5027CE676D551A2BDFE6C04,0EDF28B413735DC197E24A5AA46B188C
3,9,77D3F03B15B1CFEE59C5D16D0BE37123,0EED0BAB1E6211E9997EFA163E3BC92C
4,8,ABD03ACB00C00FE88EB701362C91F463,10EF07CC6EEC0BD16EFC9069C8D4C02D
5,4,7FAE1993C5027CE676D551A2BDFE6C04,1D74D37FA4D45B83F416CDDB677E6EBA
6,2,5E0F845AA9A537AAD2DD3E0FB248A44E,2432C61399654853656C3A9E96D691A8
7,0,ABD03ACB00C00FE88EB701362C91F463,29C2FB940CD1EAF39D8BF1AFCA0E23B3
8,3,ABD03ACB00C00FE88EB701362C91F463,2A8F77A459506726759AE4FB9C805504
9,4,77D3F03B15B1CFEE59C5D16D0BE37123,37DFB171EB069D6050FF04026321A82E
10,8,7FAE1993C5027CE676D551A2BDFE6C04,3CAE2E4FB80F036142E14085CBA91547
11,10,7FAE1993C5027CE676D551A2BDFE6C04,443B1E0EB95C304E1695AE1093C09CA9
12,1,7FAE1993C5027CE676D551A2BDFE6C04,47F7C1F4C2D5515A0CD260621108E4CF
13,1,77D3F03B15B1CFEE59C5D16D0BE37123,496ABDD2CE176B1C2D8DFC012CE545CA
14,2,ABD03ACB00C00FE88EB701362C91F463,4C13098DC9F7734C0055465EE5B6C80B
15,8,77D3F03B15B1CFEE59C5D16D0BE37123,5E278A45E260F9D1924C6B486E6B462F
16,2,77D3F03B15B1CFEE59C5D16D0BE37123,663F8287133D71ECAEE1982FBF63E500
17,0,77D3F03B15B1CFEE59C5D16D0BE37123,72F5B7EEB6C88A541413B840C52EA8D8
18,7,77D3F03B15B1CFEE59C5D16D0BE37123,79FDFCE2316E90CBE04CD187A25DA14F
19,1,5E0F845AA9A537AAD2DD3E0FB248A44E,7CC7CF85CC4B366B592FDF236A4196CC
20,0,D597C271A829F7FBE0C01FD4109854EE,7F0CAA108998908EB978E50D7971B666
21,9,7FAE1993C5027CE676D551A2BDFE6C04,80203BE21F599D39C8B7B3CB06ED3D54
22,1,ABD03ACB00C00FE88EB701362C91F463,807897544A88123E07CB0F01065DF210
23,10,77D3F03B15B1CFEE59C5D16D0BE37123,958522295D23EABC5B09646C9C300D74
24,7,ABD03ACB00C00FE88EB701362C91F463,98A54F64158ACE10564D5C481FA8DE88
25,5,ABD03ACB00C00FE88EB701362C91F463,9A106F283B62534DE8815F97130B3B00
26,3,7FAE1993C5027CE676D551A2BDFE6C04,9F8A7CFBD723CC27F9120A8FC895DC61
27,6,ABD03ACB00C00FE88EB701362C91F463,A1806944F40B79580FF2E2003F282473
28,4,ABD03ACB00C00FE88EB701362C91F463,A1D07850B9CB96C827C3352ECF66962F
29,4,D597C271A829F7FBE0C01FD4109854EE,AD0BD04A2E7C265BB80D57AF6F93CEDB
30,0,7FAE1993C5027CE676D551A2BDFE6C04,C1AA0DBAB609746AC466F362E4B80ACE
31,0,C540C42A14EA11E9B4A4FA163E3BC92C,C541489614EA11E9B4A4FA163E3BC92C
32,1,C540C42A14EA11E9B4A4FA163E3BC92C,C5417A1114EA11E9B4A4FA163E3BC92C
33,2,C540C42A14EA11E9B4A4FA163E3BC92C,C541861214EA11E9B4A4FA163E3BC92C
34,3,C540C42A14EA11E9B4A4FA163E3BC92C,C541919614EA11E9B4A4FA163E3BC92C
35,4,C540C42A14EA11E9B4A4FA163E3BC92C,C5419C4A14EA11E9B4A4FA163E3BC92C
36,0,5E0F845AA9A537AAD2DD3E0FB248A44E,C9894D96FB7578706D9DC0F2EA347408
37,2,D597C271A829F7FBE0C01FD4109854EE,CAC1CBA8E532E87B6E40B51BA02A21A1
38,1,D597C271A829F7FBE0C01FD4109854EE,CB43F5ACEC859A79D44B11EB311EEA6F
39,2,7FAE1993C5027CE676D551A2BDFE6C04,DD21F9B31A4B17DD76D46B0B99C2AA08
40,3,D597C271A829F7FBE0C01FD4109854EE,DEAD3CC2F66CAB4F6D8595AEFB4F50B4
41,3,77D3F03B15B1CFEE59C5D16D0BE37123,E9917B17B4A060F8F8F2B4B649469E3A
42,5,77D3F03B15B1CFEE59C5D16D0BE37123,EBAECE50F3A9E4E58319D664A4D6542E
43,6,77D3F03B15B1CFEE59C5D16D0BE37123,F5CDBDCDF75DFAA1A6BA541A72E4EAD8

In [44]:
df_formulaire_question_choix  #id des choix pour les questions de type choix
#question_id à joindre avec id de df_formulaire_question

,choix_order,choix_id,question_id
0,0,4C6AE4E18514140E78D6116F51E7DDEB,006F52E9102A8D3BE2FE5614F42BA989
1,1,C3AE13B68907389B5DAAD4C19E4E9816,006F52E9102A8D3BE2FE5614F42BA989
2,0,83DFF3966C9101CA46EDEBCF7C685810,013D407166EC4FA56EB1E1F8CBE183B9
3,1,A7ACD0346943D0C4BF2AB3B45C074E7C,013D407166EC4FA56EB1E1F8CBE183B9
4,0,C6212798B661ABC546CD2B6F5B6F596D,02522A2B2726FB0A03BB19F2D8D9524D
...,...,...,...
565,1,CB1597C6D9D4B5CFF7898A6D46C892D2,FA7CDFAD1A5AAF8370EBEDA47A1FF1C3
566,0,A2E19C8756B94B17676101F1A80EC189,FBD7939D674997CDB4692D34DE8633C4
567,1,FE5D8C00C7E6E2FA3157CF9929E60238,FBD7939D674997CDB4692D34DE8633C4
568,0,7BDF486C2DD1A1F1D65C3EBE95C07956,FC221309746013AC554571FBD180E1C8
569,1,5ECF76CF3CD2F3393445A2DE9428941D,FC221309746013AC554571FBD180E1C8

In [46]:
df_formulaire_question_choix.describe()

       choix_order
count   570.000000
mean      0.689474
std       0.873388
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       5.000000

In [47]:
df_formulaire_reponse
#node_id: id du client

,node_id,valeur_actee,non_concerne_acte,commentaire_acte,question_id
0,2c90f5883f44af68013f564a1326558a,c3ae13b6-8907-389b-5daa-d4c19e4e9816,\0,NaN,006F52E9102A8D3BE2FE5614F42BA989
1,2c90f5883f44af68013f564a1326558a,scellées pour RX,\0,NaN,01161AAA0B6D1345DD8FE4E481144D84
2,2c90f5883f44af68013f564a1326558a,83dff396-6c91-01ca-46ed-ebcf7c685810,\0,Oui\n2,013D407166EC4FA56EB1E1F8CBE183B9
3,2c90f5883f44af68013f564a1326558a,3816c6a2-2a60-e9f2-1430-954151ba8d1a,\0,NaN,02522A2B2726FB0A03BB19F2D8D9524D
4,2c90f5883f44af68013f564a1326558a,fa4a1c04-c8b1-b7a5-fe48-4351eb44bcca,\0,"nous recevons des matières dangereuses (gazole, solvant, acide,...) en grande quantité et nous expédions/transportons instersite (venissieux/st priest, La valbonne) de petites quantités ~1000L",02E74F10E0327AD868D138F2B4FDD6F0
...,...,...,...,...,...
117075,ff8081817528e71501754135cdfb6d7b,NaN,\0,NaN,F033AB37C30201F73F142449D037028D
117076,ff8081817528e71501754135cdfb6d7b,NaN,\0,NaN,F457C545A9DED88F18ECEE47145A72C0
117077,ff8081817528e71501754135cdfb6d7b,NaN,\0,NaN,FBD7939D674997CDB4692D34DE8633C4
117078,ff8081817528e71501754135cdfb6d7b,NaN,\0,NaN,FD86425BAD0511E7B3CE001851D17886
117079,ff8081817528e71501754135cdfb6d7b,NaN,\0,NaN,FE9FC289C3FF0AF142B6D3BEAD98A923

In [48]:
df_formulaire_reponse.describe()

,node_id,valeur_actee,non_concerne_acte,commentaire_acte,question_id
count,117080,93777,117080,18920,117080
unique,597,10003,2,14996,316
top,4028807d16245e4d01162478b54b7da4,ce8bb558-c8c9-443b-4d13-88c57d1d9043,\0,Oui,02E74F10E0327AD868D138F2B4FDD6F0
freq,285,457,114971,206,576

In [49]:
df_formulaire_page_questions

,question_order,page_id,question_id
0,9,47F7C1F4C2D5515A0CD260621108E4CF,006F52E9102A8D3BE2FE5614F42BA989
1,1,80203BE21F599D39C8B7B3CB06ED3D54,01161AAA0B6D1345DD8FE4E481144D84
2,11,C5419C4A14EA11E9B4A4FA163E3BC92C,01161AAA0B6D1345DD8FE4E481144D84
3,8,F5CDBDCDF75DFAA1A6BA541A72E4EAD8,013D407166EC4FA56EB1E1F8CBE183B9
4,4,F5CDBDCDF75DFAA1A6BA541A72E4EAD8,02522A2B2726FB0A03BB19F2D8D9524D
...,...,...,...
349,11,DD21F9B31A4B17DD76D46B0B99C2AA08,FC221309746013AC554571FBD180E1C8
350,6,72F5B7EEB6C88A541413B840C52EA8D8,FC490CA45C00B1249BBE3554A4FDF6FB
351,11,7CC7CF85CC4B366B592FDF236A4196CC,FD86425BAD0511E7B3CE001851D17886
352,6,4C13098DC9F7734C0055465EE5B6C80B,FE131D7F5A6B38B23CC967316C13DAE2
353,1,663F8287133D71ECAEE1982FBF63E500,FE9FC289C3FF0AF142B6D3BEAD98A923